package com.yzh.ssm.dao;

import com.yzh.ssm.model.MotorHome;
import com.yzh.ssm.model.MotorHomeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MotorHomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    long countByExample(MotorHomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int deleteByExample(MotorHomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int insert(MotorHome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int insertSelective(MotorHome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    List<MotorHome> selectByExample(MotorHomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    MotorHome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int updateByExampleSelective(@Param("record") MotorHome record, @Param("example") MotorHomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int updateByExample(@Param("record") MotorHome record, @Param("example") MotorHomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int updateByPrimaryKeySelective(MotorHome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table motorhome
     * @mbg.generated 2018-11-23 09:33:01
     */
    int updateByPrimaryKey(MotorHome record);
}